export declare const tsconfig = "./tsconfig.json";
export declare const packagejson = "./package.json";
export declare const dtsEntry = "index.d.ts";
export declare const output = "./index.js";
export declare const input = "./src/index";
export declare const outputDir = "npm";
export declare const esmExt: string[];
export declare const cjsExt: string[];
export declare const esmMiddleNames: string[];
export declare const cjsMiddleNames: string[];
